### ISSUE TITLE
Favorite insights don't persist the ⭐ indication

### ISSUE THREAD

**Issue by elongl** [PostHog/posthog#11130]
## Bug description

If I mark an insight as a favorite (⭐) and then refresh, the insight is no longer marked as a favorite although it is (can see it in Favorites).

<img width="390" alt="image" src="https://user-images.githubusercontent.com/30181361/182802236-9ecf0531-899c-4f25-ae86-bc233cefdc2f.png">

Note that I'm in the _Favorites_ tab and that _Bug example_ is not starred.
## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by pauldambra** [comment]
@elongl Thanks for the bug report 💖 I've just merged a fix. Should be visible for you within 30 minutes

**Comment by elongl** [comment]
@pauldambraThat was really fast, appreciate it.
If you could address [this](https://github.com/PostHog/posthog/issues/11129) issue it would be amazing!
We really want to integrate PostHog into our product but can't due to this bug.
Thanks a lot.

**Comment by elongl** [comment]
@pauldambra That was really fast, appreciate it.
If you could address [this](https://github.com/PostHog/posthog/issues/11129) issue it would be amazing!
We really want to integrate PostHog into our product but can't due to this bug.
Thanks a lot.

**Comment by nmazuz** [comment]
Hi I still experience this issue
Cloud version
![image](https://user-images.githubusercontent.com/2725276/212874754-296ffc45-e169-4c7a-bac3-0cba397859ba.png)

**Comment by pauldambra** [comment]
Hey @nmazuz do you only have this error when trying to favourite an insight? I've just checked and I can favourite insights on PostHog Cloud. 

The error you have shown has a CORS error... It looks like you are using PostHog Cloud? Do you run it behind a proxy?

**Comment by nmazuz** [comment]
Hi Paul

No, it happened when the "init" function got called.
I am using the cloud version (not behind a proxy)
I tried to use the pixel in Shopify custom pixels (which is a very common
place to use pixels and collect user event) and I got this error only there.
it seems because shopify send the requests with "null" value in the origin
header, what cause this error on your end,

Any chance that you can ignore the null value on the server side on the
cloud version?

**Comment by pauldambra** [comment]
Hey @nmazuz can you copy the request out of the dev tools so I can see how it is being sent? Adding a test to our capture end point for `origin is null` and `origin="null"` doesn't generate the CORS error

![Screenshot 2023-01-17 at 14 31 37](https://user-images.githubusercontent.com/984817/212925704-0f312eeb-8917-4833-8964-08d9d9ce117d.png)
