### ISSUE TITLE
rrweb element masking with :not selectors

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#20100]
see 

* https://posthoghelp.zendesk.com/agent/tickets/8312
* https://posthoghelp.zendesk.com/agent/tickets/8807

we've had two reports that masking elements using a :not selector didn't work for the user
a quick check with jsbin showed it working for a trivial example, but two reports is suspicious and we should dig in more thoroughly

e.g.

> The maskTextSelector is set to ':not([data-record="true"])'
> However, as you can see in the image, the span element has data-record attribute correctly set, but it's still masked in the video.

**Comment by FreddieHoy** [comment]
@pauldambra Hey I've run in to the same issue! Looks like the use of 

```
:not()
```
Isn't working. I've tried

```
*:not(...)
:not(.ph-show)
:not(#phShow)
```

But if I am hiding just selective items (instead of the inverse with :not) then it works. IE using:

```
.hide
#hide
etc..
```

I'm using tailwind and next.js I wonder if that is an issue?

What other information can I provide?

Do you know when this might be worked on?

Thanks

**Comment by pauldambra** [comment]
hey @FreddieHoy thanks for letting us know... we're going to focus on "correctness" for a few sprints so might be able to pull this in...

When I made a little reproduction using basic html in htmlfiddle the `:not` selector worked fine. If you could make a reproducible example that would be amazing 

(cc @daibhin)

**Comment by pauldambra** [comment]
^^^ @daibhin (in case you can look at this today :))

**Comment by daibhin** [comment]
Great, thanks @FreddieHoy! Let me reproduce this today and find out where the selector isn't matching

**Comment by daibhin** [comment]
This is caused by a bug in our underlying recording tool ([rrweb](https://github.com/rrweb-io/rrweb))

The elements are correctly evaluated (the "visible" text returns `false`)
But its ancestors are also considered... And because of the `:not` the wrapping div does not pass, hence causing the "visible" text to be masked

<img width="412" alt="Screenshot 2024-04-05 at 15 52 49" src="https://github.com/PostHog/posthog/assets/6685876/d3e25063-2488-4766-89a3-312bf7aaf258">

I think this bug might have been inadvertently resolved by https://github.com/rrweb-io/rrweb/pull/1349. We're in the process of [upgrading to the latest version](https://github.com/PostHog/posthog-js/pull/1115) which includes that change. I will prioritise that upgrade and test this again once shipped

**Comment by FreddieHoy** [comment]
@daibhin @pauldambra Fantastic news, thanks for being so quick on this! Legends 🙌

**Comment by daibhin** [comment]
Have an update to the docs ready to go so closing this one out

**Comment by mwalcher** [comment]
@daibhin This still isn't working and I think needs to be reopened. Your proposed solution with `maskTextFn` doesn't work because that function doesn't have access to the `element` parameter like the `maskInputFn`, so we can't check the data attribute exists for text elements, only inputs.

I'm on the latest version of the posthog package and I have a screenshot of the session recording option types:

![Screenshot 2024-04-09 101935](https://github.com/PostHog/posthog/assets/11944153/d49dd171-1eaa-4865-b70c-06c51b4af6cb)

**Comment by daibhin** [comment]
@mwalcher ah, I think that might just be a typing issue on our end! You can see that the rrweb method does pass out the parent element: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb-snapshot/src/types.ts#L158

Will reopen until we get https://github.com/PostHog/posthog-js/pull/1122 over the line

**Comment by daibhin** [comment]
Just checked on the latest version of posthog-js (`1.120.3`) and the correct types now exist

**Comment by mwalcher** [comment]
Thank you for resolving that so quickly @daibhin! I've updated to the latest version and everything is working as expected now.

I just had a suggestion for the docs because I think it will be handy for others as well. I want to use the data attribute to unmask sections of the page, so I'll add the data attribute to a parent element and everything nested in that element will be unmasked.

This is the code I'm using for the `maskTextFn`:
```
session_recording: {
    maskTextSelector: "*",
    maskTextFn: (text, element) => {
      const maskedText = '*'.repeat(text.length);
      if (!element) return maskedText;
      const isElementOptedIn = element.closest("[data-record='true']");
      return isElementOptedIn ? text : maskedText;
    },
},
```

The key here is using `element.closest("[data-record='true']")` to check for the data attribute instead of `element.dataset['record'] === 'true'` because it will find the element itself if it has the data attribute or any parent element that has the data attribute. This same function also works for `maskInputFn` as well.

**Comment by daibhin** [comment]
@lobaorn it will depend on the version of the `posthog-js` you're running and not the Docker version. I suggest making sure that you're running the latest version of the PostHog Web SDK by using the snippet or upgrading the NPM package to `v1.120.3` or higher
