### ISSUE TITLE
self-host bug list

### ISSUE THREAD

**Issue by straxico** [PostHog/posthog#28804]
hi i try use posthog self-host but i pause on start and spend many hour for find

1. latest instalable commit is 579408c765dc6a33cba571a558b553c1fff771c5  you most use `579408c765dc6a33cba571a558b553c1fff771c5` as docker tag for self-host
#28254 
#28448

2. events tab data not  show and cant use events for filter
#26107
 you most add this code to docker-compose
```
   property-defs-rs:
        image: ghcr.io/posthog/posthog/property-defs-rs:master
        build:
            context: posthog/rust/
            args:
                BIN: property-defs-rs
        restart: on-failure
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            KAFKA_HOSTS: 'kafka:9092'
            SKIP_WRITES: 'false'
            SKIP_READS: 'false'
            FILTER_MODE: 'opt-out'
```

3. live activity not work 
#26106
its fix on #7724fd847d45cc5c731c4e05cf47ef4790090435 but cant useable for me because error number 1

4. when i start record sessons all thing ok but after about 30 min . all things stop. all container up but panel not load and events not save . i give storage slow error but i cant find more details

**Comment by dix105** [comment]
@moufmouf  could you please tell me where shoudl i put NEW_CAPTURE_ENDPOINT this in my docker-compse.base.yml file

**Comment by moufmouf** [comment]
Sure!

Put it in the env vars of the "worker" service inside `docker-compse.base.yml`.

```
worker:
  environment:
       NEW_CAPTURE_ENDPOINT: '/e/'
```

I guess a better way would be to put that in the `docker-compse.yml` (it is the one we are supposed to overload) but I haven't tried that yet.

**Comment by dix105** [comment]
@moufmouf  thanks 
can you also look this issue [](https://github.com/PostHog/posthog/issues/28842)

**Comment by dix105** [comment]
@straxico can you please look into this issue also https://github.com/PostHog/posthog/issues/28842

**Comment by straxico** [comment]
> [@straxico](https://github.com/straxico) can you please look into this issue also [#28842](https://github.com/PostHog/posthog/issues/28842)

ok i see

**Comment by straxico** [comment]
> [@straxico](https://github.com/straxico) can you please look into this issue also [#28842](https://github.com/PostHog/posthog/issues/28842)

i have same error and after bind `user_defined_function.xml` and `user_scripts` its work fine. see top post i update it

![Image](https://github.com/user-attachments/assets/e8c0d994-3f9f-44a5-9fd0-686e1eb90b9b)

**Comment by dix105** [comment]
@straxico  i tried but got same error.

**Comment by solarvm** [comment]
@moufmouf @straxico 
for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
```
2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=phc_N6mtVTAKHr2cKJsGHUzv3IReUiS6vR3tgR5vD8B96eX x_forwarded_for=...EDITED...
2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=phc_N6mtVTAKHr2cKJsGHUzv3IReUiS6vR3tgR5vD8B96eX x_forwarded_for=...EDITED...

```
has injection of that var resolved the issue completely for you?

**Comment by straxico** [comment]
> [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> 
> ```
> 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> ```
> 
> has injection of that var resolved the issue completely for you?

i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ .
this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/  to /e/

**Comment by dix105** [comment]
@straxico i have added 
 - ./posthog/posthog/idl:/idl
            - ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ./posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
            - ./docker/clickhouse/config.d/default.xml:/etc/clickhouse-server/config.d/default.xml
            - ./posthog/posthog/user_scripts:/var/lib/clickhouse/user_scripts
            - ./posthog/docker/clickhouse/user_defined_function.xml:/etc/clickhouse-server/user_defined_function.xml
            - clickhouse-data:/var/lib/clickhouse

but issue remain same

**Comment by solarvm** [comment]
> > [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> > ```
> > 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > has injection of that var resolved the issue completely for you?
> 
> i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ . this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/ to /e/

Still getting hits on that endpoint. Var is set at both composer files (base and override).
Just wonder maybe it should exist during the first db migrations? (i.e. do i need to reinstall the whole thing) or is it just a pure runtime var?

**Comment by moufmouf** [comment]
@solarvm 
To check if this is working, check in the network tabs of your dev-tools in your browser. You should not see any HTTP 403 anymore.

After applying the change, you can still occasionally see "Forbidden" errors because the web pages already loaded before you made the change will keep hitting the `/i/v0/e` endpoint.

**Comment by straxico** [comment]
> > > [@moufmouf](https://github.com/moufmouf) [@straxico](https://github.com/straxico) for item 4 (CSRF issue). I've passed the var `NEW_CAPTURE_ENDPOINT` into worker/web containers, however still getting those 403s in logs:
> > > ```
> > > 2025-02-19T04:13:06.466025Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > > 2025-02-19T04:13:06.466096Z [warning  ] Forbidden (Origin checking failed - https://...EDITED... does not match any trusted origins.): /i/v0/e/ [django.security.csrf] container_hostname=5d5165896b98 host=ph....EDITED... pid=534 tid=129292627290432 token=EDITED x_forwarded_for=...EDITED...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > has injection of that var resolved the issue completely for you?
> > 
> > 
> > i think your env not applyd. when set NEW_CAPTURE_ENDPOINT: '/e/' and run . not see any request point to /i/v0/e/ . this way dont solve /i/v0/e/ csrf issues, its change endpoint from /i/v0/e/ to /e/
> 
> Still getting hits on that endpoint. Var is set at both composer files (base and override). Just wonder maybe it should exist during the first db migrations? (i.e. do i need to reinstall the whole thing) or is it just a pure runtime var?

dont need reinstall . when i change env and restart its apply.
its my code
```yaml
    web:
        extends:
            file: docker-compose.base.yml
            service: web
        command: /compose/start
        volumes:
            - ./compose:/compose
        image: posthog/posthog:579408c765dc6a33cba571a558b553c1fff771c5
        environment:
            SENTRY_DSN: 'https://aaaaaaaaa@sentry.aaaaaa.com/a'
            SITE_URL: https://posthog.jajiga.com
            SECRET_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            OBJECT_STORAGE_ACCESS_KEY_ID: 'object_storage_root_user'
            OBJECT_STORAGE_SECRET_ACCESS_KEY: 'object_storage_root_password'
            OBJECT_STORAGE_ENDPOINT: http://objectstorage:19000
            NEW_CAPTURE_ENDPOINT: '/e/'
            OBJECT_STORAGE_ENABLED: true
            TRUST_ALL_PROXIES: true
            IS_BEHIND_PROXY: true
            DISABLE_PAID_FEATURE_SHOWCASING: true
            OPT_OUT_CAPTURE: true
            ENCRYPTION_SALT_KEYS: aaaaaaaaaaaaaaaaaaaaaaaaaa
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - objectstorage
```

**Comment by solarvm** [comment]
@straxico well, i have the same. And checked if env properly loaded
```
root@trw-pa3:~# docker exec -it opt-web-1 'env' | grep NEW_CAPTURE
NEW_CAPTURE_ENDPOINT=/e/
```
I think @moufmouf is right, those requests are some leftovers from already loaded pages

**Comment by paul-uz** [comment]
How do I use a tag when using the start up script? I tried putting `579408c765dc6a33cba571a558b553c1fff771c5` but I get the following error

```
Grabbing latest apt caches
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                           
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu noble-updates InRelease                             
Hit:4 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu noble-backports InRelease                           
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease                                         
Reading package lists... Done                                                                            
Building dependency tree... Done
Reading state information... Done
98 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Installing PostHog 🦔 from Github
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.43.0-1ubuntu7.2).
0 upgraded, 0 newly installed, 0 to remove and 98 not upgraded.
Checking out specific commit hash: 579408c765dc6a33cba571a558b553c1fff771c5
fatal: reference is not a tree: 579408c765dc6a33cba571a558b553c1fff771c5
```

**Comment by dix105** [comment]
@paul-uz   first create setup with latest posthog and move to posthog directory and type command git pull --unshallow and then checkout command

**Comment by paul-uz** [comment]
@dix105 i got a bit further, but even that "working" commit is broken for me, see https://github.com/PostHog/posthog/issues/28995

**Comment by pauldambra** [comment]
ok, hoping at least some of this is fixed here https://github.com/PostHog/posthog/pull/29018

i'm in GMT and about to go into a meeting, so unlikely to test this personally today

**Comment by dix105** [comment]
@pauldambra  

now i got unable to prepare context: path "/root/never" not found
how i can fix this

**Comment by pauldambra** [comment]
Hey all, 

I've confirmed the install script works again on Ubuntu 24 on the recommended specs. Thanks for letting us know!

@straxico I'm just running through the setup process again on my self-hosted instance but would love to know which of the items listed are fixed for you now

**Comment by pauldambra** [comment]
@straxico I note you linked to #26106  after it was closed... is it still broken for you?

**Comment by agwidarsito** [comment]
Hello All,

I have spent the better part of the last 10 days trying to work out if there is a stable version of this app. I believe there is not. Very similarly to everyone here I have encountered the same set of issues and resolved them in the same way.

If you try and use a newer version of the containers (as of 23/02/2025) your will run into a Clickhouse migration issues and rust related issues with Cyclotron (although this doesn't really matter as you can use the app anyway without it). Namely it will report there is no migration table available. Even when I fixed that it's missing actual migration tables, so no go.

If you run older container versions (around 25-30 days old) you'll run into these issues stated.

Even older versions again and it won't work as the docker-compose script is not designed for older versions.

Further to this, even with all the above solutions in place session recoding will not work due to an issue with the plug-in agent. Namely you will get an error like:

`{"level":"error","time":1739928755891,"pid":76,"hostname":"68c384c03347","sessionId":"01951b2a-7bfb-77e0-953e-dea67d44fef3","partition":0,"teamId":1,"topic":"session_recording_snapshot_item_events","oldestKafkaTimestamp":null,"bufferCount":0,"msg":"[MAIN] :firecracker: [session-manager] flush timed out"}`

It's something to do with how the agent flushes data to Minio. However, changing any environment variables won't fix it. So it would be a source code change. Which is a waste of time as it will get merged to the lastest and that has like 20 more other bugs you'd need to fix too.

**Tldr:**
Honestly, I think these guys are just playing us. At every corner they want you to use the cloud app. They purposely don't tag there stable versions to make hosting it yourself virtually impossible.

So essentially, it's either pay for the cloud app or don't bother. These guys are just open source in name only.
We ended up using [highlight.io](https://www.highlight.io/) works fine.

**Comment by paul-uz** [comment]
After facing these issues myself, I am inclined to agree with you.

Playing devil's advocate however, they do offer a free tier.

But ultimately, they either need to get their shit together or just be honest and drop the self hosted version altogether.

**Comment by dix105** [comment]
@agwidarsito @paul-uz I have fixed all the issues, and the self-hosted PostHog is now running without errors.

**Comment by pauldambra** [comment]
> Namely you will get an error like:

{"level":"error","time":1739928755891,"pid":76,"hostname":"68c384c03347","sessionId":"01951b2a-7bfb-77e0-953e-dea67d44fef3","partition":0,"teamId":1,"topic":"session_recording_snapshot_item_events","oldestKafkaTimestamp":null,"bufferCount":0,"msg":"[MAIN] :firecracker: [session-manager] flush timed out"}

@agwidarsito it's hard to diagnose issues from a single log line

i've just updated to the latest minio in the self-hosted image. and validated that works in my self-hosted install and my local dev environment

**Comment by pauldambra** [comment]
updating on the items in the description

| status | Issue                                     | Status / Notes |
|------|------------------------------------------|---------------|
| ✅   | Latest Installable Commit               | The latest commit on `master` installs, upgrades, and runs successfully on Ubuntu 24 in testing. |
| ✅   | Events Tab Not Showing Data             | Resolved—events ingest and propdefs service inclusion make filters available. |
| ❌   | Live Activity Not Working               | Confirmed not working in testing; will investigate. |
| ❓   | CSRF Issue with `/i/v0/e/` Endpoint     | Cannot replicate; needs more info. |
| ❌   | Some ClickHouse Function Not Working    | Confirmed - will test suggested solution |
| ❓   | Session Recording Causes System Failure | Cannot replicate; needs more info. |

**Comment by straxico** [comment]
hi @pauldambra i update to latest commit and its work. Events Tab Not Showing Data solved.  ClickHouse Function solved.
Live Activity not work. caddy config need change. when my siteUrl is https://posthog.example.com , browser try to connect to  https://posthog.example.com:8666/events and caddy cant hangle it with bellow config
```
$DOMAIN, http://, https:// {
encode gzip zstd
reverse_proxy http://web:8000
reverse_proxy http://livestream:8666
}
```
i get ssl error on browser.

its need add another domain for livestream or remove port and add a prefix route like /live/ 

and CSRF Issue with /i/v0/e/ Endpoint exist.

i suggest to yyou dont use localhost as domain for test

**Comment by pauldambra** [comment]
thanks @straxico 

I don't use localhost for tests... I'm running my own posthog at ph.pauldambra.dev. so that i can test in situations like this.

---

Yep, livestream still not there for sure

@fuziontech does the above on livestream help you immediately jump to a solution 🤞 

---

> CSRF Issue with /i/v0/e/ Endpoint exist.

Can you share whether you've changed config here? I don't think you should even be hitting `/i/v0/e`. I _think_ what's happening is that new rust capture is being routed to django... I can probably fix django here anyway but I don't think that would solve the underlying problem and probably not work - so want to understand what config to set to get into the state myself

**Comment by dix105** [comment]
@pauldambra 

![Image](https://github.com/user-attachments/assets/78761ab6-a699-4295-9d1d-7e9b09dbbbc9)

why there is no transformation is appear is it paid feature ?

**Comment by ernesto-keeper** [comment]
## Solution for Selfhosted Installation Issues

After reviewing past issues and troubleshooting through three fresh installs, I have identified the following:

- The current `master` branch (as of 2024-03-04) does not work out of the box.
- Live events are still broken, but they are not essential. You can configure the `Caddyfile` to listen on port `8666` and experiment with a working configuration for your deployment.
- To ensure proper functionality, update `docker-compose.yml` with the following environment variables per service:

### web:
```yaml
NEW_CAPTURE_ENDPOINT: '/e/'
TRUST_ALL_PROXIES: true
IS_BEHIND_PROXY: false
DISABLE_PAID_FEATURE_SHOWCASING: true
OPT_OUT_CAPTURE: true
NEW_ANALYTICS_CAPTURE_EXCLUDED_TEAM_IDS: 1
```

### worker:
```yaml
NEW_CAPTURE_ENDPOINT: '/e/'
NEW_ANALYTICS_CAPTURE_EXCLUDED_TEAM_IDS: 1
```

### plugins: (Not necessarily required, but included for completeness)
```yaml
NEW_CAPTURE_ENDPOINT: '/e/'
NEW_ANALYTICS_CAPTURE_EXCLUDED_TEAM_IDS: 1
```

**Important:**

Before running the following command, make sure to back up docker-compose.yml, as this command will remove all custom configurations: ```/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/upgrade-hobby)"```

Hope this helps! 🚀

**Comment by pauldambra** [comment]
hey @ernesto-keeper 

> The current master branch (as of 2024-03-04) does not work out of the box.

Are you saying the install doesn't work for you? I validated it worked on 25th Feb.

(I'm not convinced those settings are valid for all users btw but thanks for sharing they worked for you)

**Comment by ernesto-keeper** [comment]
> hey [@ernesto-keeper](https://github.com/ernesto-keeper)
> 
> > The current master branch (as of 2024-03-04) does not work out of the box.
> 
> Are you saying the install doesn't work for you? I validated it worked on 25th Feb.
> 
> (I'm not convinced those settings are valid for all users btw but thanks for sharing they worked for you)

Apologies for the confusion in my wording, @pauldambra. The master branch installs the PostHog server successfully using: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"`

After installation, you can access the PostHog interface without any issues— all migrations are completed successfully, and no additional changes are required. Everything works as expected except for the Live Events menu, which does not display data and shows all the failed requests to port 8666.

The issues arise in the second phase: integrating my application with the server. To enable proper tracking, the necessary configurations must be added to the docker-compose.yml file. Without these changes, correct tracking does not show, and the same is true for heatmaps, custom events, and web-vitals in the Posthog server.

For context, I was using the Node.js package: `"posthog-js": "^1.227.0"`

**Comment by dix105** [comment]
@pauldambra can you clarify my question 
https://github.com/PostHog/posthog/issues/28804#issuecomment-2697519472

**Comment by pauldambra** [comment]
hey @dix105 it's really best to open fresh issues, these long grab bag issues things get lost 🫠

I think it's https://github.com/PostHog/posthog/pull/29517 will test shortly

**Comment by pauldambra** [comment]
@straxico hope you don't mind me locking this but it's really unmanageable once multiple folk start adding unrelated things to an issue 🙈

**Comment by pauldambra** [comment]
@dix105 i've updated my self hosted instance and can see transformations again, so that should be sorted for you

**Comment by pauldambra** [comment]
updating on the items in the description

the two that we can't replicate please open a new issue if you are facing it with how to replicate. thanks!

| status | Issue                                     | Status / Notes |
|------|------------------------------------------|---------------|
| ✅   | Latest Installable Commit               | The latest commit on `master` installs, upgrades, and runs successfully on Ubuntu 24 in testing. |
| ✅   | Events Tab Not Showing Data             | Resolved—events ingest and propdefs service inclusion make filters available. |
| ✅    | Live Activity Not Working               | Resolved - fixed here https://github.com/PostHog/posthog/pull/31948 |
| ❓   | CSRF Issue with `/i/v0/e/` Endpoint     | Cannot replicate; needs more info. |
| ✅  | Some ClickHouse Function Not Working    | Confirmed - fix here https://github.com/PostHog/posthog/pull/29175 |
| ❓   | Session Recording Causes System Failure | Cannot replicate; needs more info. |
