### ISSUE TITLE
Dashboards change position randomly

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5262]
## Bug description

See recording below, positions change just by refreshing. Additionally, if I open graph 3 and update it (save to dashboard updating same panel) the updated panel gets thrown into position one of the dashboard.

![image](https://user-images.githubusercontent.com/5864173/126525962-d592a08c-98cb-4435-bc95-9e67de18a833.gif)

## Expected behavior

I would expect my dashboards to stay the same unless I change them.

## How to reproduce

See instructions above.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
This looks like a pretty frustrating issue would be awesome to fix it.

**Comment by liyiy** [comment]
I am not seeing this bug anymore? Can someone else also confirm @paolodamico @alexkim205 @marcushyett-ph

**Comment by marcushyett-ph** [comment]
If you try making the window smaller and larger I saw this happen quite a
bit?

**Comment by liyiy** [comment]
hmm is that a bug though? The graphs will shift if you change the window size but they'll still stay in the same position after refreshing

**Comment by marcushyett-ph** [comment]
But they shift really weirdly like the bottom one becomes the top one etc.

However, you’re right they persist after refreshing so I’m not sure that’s
actually what this bug was trying to capture. And that’s not as severe- so
perhaps this specific bug is resolved

**Comment by paolodamico** [comment]
Actually the bug when resizing windows is different (#4312) and the problem there is we actually need a grid with strongly defined positions (which would account for the changes in screen sizes too) rather than the fluid thing that we have right now.

I could still reproduce this bug. Happens when I add stuff to a dashboard, sometimes it'll get added at the first position, sometimes at the last one, sometimes second to last, and refreshing the first time changes the position before it's preserved, but indeed this might not be too critical right now as if you really care about positioning and you move it, that new position is in fact properly preserved. Downgrading priority unless someone has a strong argument against this.
